# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x0fimageclassifier\"\x07\n\x05\x45mpty\"4\n\x0cImageRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"K\n\x14\x43lassificationResult\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x32X\n\rImageStreamer\x12G\n\x0cStreamImages\x12\x16.imageclassifier.Empty\x1a\x1d.imageclassifier.ImageRequest0\x01\x32g\n\x0fImageClassifier\x12T\n\x08\x43lassify\x12\x1d.imageclassifier.ImageRequest\x1a%.imageclassifier.ClassificationResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_IMAGEREQUEST']._serialized_start=41
  _globals['_IMAGEREQUEST']._serialized_end=93
  _globals['_CLASSIFICATIONRESULT']._serialized_start=95
  _globals['_CLASSIFICATIONRESULT']._serialized_end=170
  _globals['_IMAGESTREAMER']._serialized_start=172
  _globals['_IMAGESTREAMER']._serialized_end=260
  _globals['_IMAGECLASSIFIER']._serialized_start=262
  _globals['_IMAGECLASSIFIER']._serialized_end=365
# @@protoc_insertion_point(module_scope)
