# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import backend.utils.image_pb2 as image__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in image_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ImageStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamImages = channel.unary_stream(
                '/imageclassifier.ImageStreamer/StreamImages',
                request_serializer=image__pb2.Empty.SerializeToString,
                response_deserializer=image__pb2.ImageRequest.FromString,
                _registered_method=True)


class ImageStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamImages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamImages,
                    request_deserializer=image__pb2.Empty.FromString,
                    response_serializer=image__pb2.ImageRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageclassifier.ImageStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageclassifier.ImageStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/imageclassifier.ImageStreamer/StreamImages',
            image__pb2.Empty.SerializeToString,
            image__pb2.ImageRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImageClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.stream_stream(
                '/imageclassifier.ImageClassifier/Classify',
                request_serializer=image__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__pb2.ClassificationResult.FromString,
                _registered_method=True)


class ImageClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Classify(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.stream_stream_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=image__pb2.ImageRequest.FromString,
                    response_serializer=image__pb2.ClassificationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageclassifier.ImageClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageclassifier.ImageClassifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Classify(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/imageclassifier.ImageClassifier/Classify',
            image__pb2.ImageRequest.SerializeToString,
            image__pb2.ClassificationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
